name: visudocs

services:
  mongo:
    image: mongo:8.0.5
    # ports:
    #   - 27017:27017
    volumes:
      - mongo_data:/data/db
    networks:
      - visudocs-app
  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data
    networks:
      - visudocs-app
  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: ./server/.env
    volumes:
      - ./server:/app
      - /app/node_modules
    networks:
      - visudocs-app
    ports:
      - 3000:3000
    depends_on:
      - mongo
      - redis

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: ./client/.env
    volumes:
      - ./client:/app
      - /app/node_modules
    networks: 
      - visudocs-app
    ports:
      - 5173:5173
    depends_on:
      - api

volumes:
  mongo_data:
  redis_data:
networks:
  visudocs-app:
    driver: bridge